# Site settings
title: Rooof memoria
header-img: img/home-bg.jpg
email: hellorooof@gmail.com
description: "Memoria del proyecto final ROOOF para el master en dise√±o web en BAU Barcelona"
baseurl: "/memoria"
url: "http://rooof-project.github.io/memoria/"
twitter_username: Rooof
github_username:  Rooof-Project
facebook_username:  Rooof

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
