# Site settings
title: Memoria de ROOOF
header-img: img/home-bg.jpg
email: hellorooof@gmail.com
description: "memoria de ROOOF"
baseurl: "/memoria"
url: "http://rooof-project.github.io"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
