# Site settings
title: ROOOF
header-img: img/home-bg.jpg
email: hellorooof@gmail.com
description: "ROOOF Memoria proyecto final"
baseurl: "/memoria"
url: "http://rooof-project.github.io"
twitter_username: HelloRooof
github_username:  rooof-project
facebook_username:  hellorooof

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Prose.io online editor
prose:
  rooturl: '_posts'
  siteurl: 'http://rooof-project.github.io/memoria/'
  media: 'img'
  ignore:
    - index.md
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "published"
        field:
          label: "published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "layout"
          element: "text"
          value: "post"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
