# Site settings
title: ROOOF
header-img: img/home-bg.jpg
email: hellorooof@gmail.com
description: "ROOOF Memoria proyecto final"
baseurl: "/memoria"
url: "http://rooof-project.github.io"
twitter_username: ROOOF
github_username:  rooof-project
facebook_username:  ROOOF

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
